### ISSUE TITLE
why store in a Buffer?

### ISSUE THREAD

**Issue by moimikey** [Jam3/babel-plugin-static-fs#11]
Hi,

simple question: why does the string need to be stored in a Buffer? it could be cross-browser to store it just as a string, since Base64 is just a string.

**Comment by mattdesl** [comment]
This is for compatibility with Node.js and the `fs` module, which returns a Buffer. You can use `'utf8'` encoding if you'd like it to return a string instead.

See this example which will run correctly in Node & the browser, but only because Buffer is returned by default:

```js
const fs = require('fs');
console.log(fs.readFileSync('myfile.txt').byteLength);
```
