### ISSUE TITLE
Incompatible with babel 7

### ISSUE THREAD

**Issue by ajcrites** [Jam3/babel-plugin-static-fs#12]
Using this plugin with Babel 7 results in this error:

`Cannot read property 'traverse' of null`

It seems like `path.getFunctionParent()`'s behavior has changed for babel 7.

**Comment by azu** [comment]
Maybe, It was resolved by https://github.com/Jam3/babel-plugin-static-fs/pull/13

**Comment by mattdesl** [comment]
I pushed 2.0.0 of this which upgrades to `@babel/` scoped packages, and should work with latest babel7.
